WALKING_SPOTS = {
    "台北市": [
        {
            "id": 1,
            "name": "大安森林公園",
            "address": "台北市大安區新生南路二段1號",
            "description": "台北市最大的都市公園，有寬敞的草坪與步道，非常適合帶狗散步。",
            "rating": 4.8,
            "tags": ["草地", "步道", "寵物友善"],
            "image_url": "https://picsum.photos/seed/taipei1/400/250",
        },
        {
            "id": 2,
            "name": "象山自然步道",
            "address": "台北市信義區信義路五段150巷",
            "description": "緊鄰信義區的山林步道，可俯瞰台北101，適合體力好的狗狗。",
            "rating": 4.5,
            "tags": ["山林", "步道", "景觀"],
            "image_url": "https://picsum.photos/seed/taipei2/400/250",
        },
        {
            "id": 3,
            "name": "關渡自然公園",
            "address": "台北市北投區關渡路55號",
            "description": "濕地生態豐富，設有木棧道，適合享受自然生態的散步體驗。",
            "rating": 4.6,
            "tags": ["濕地", "生態", "步道"],
            "image_url": "https://picsum.photos/seed/taipei3/400/250",
        },
    ],
    "新北市": [
        {
            "id": 4,
            "name": "淡水老街河濱步道",
            "address": "新北市淡水區中正路",
            "description": "沿著淡水河畔的步道，夕陽景色迷人，是帶毛孩散步的熱門地點。",
            "rating": 4.7,
            "tags": ["河濱", "步道", "景觀"],
            "image_url": "https://picsum.photos/seed/newtp1/400/250",
        },
        {
            "id": 5,
            "name": "碧潭風景區",
            "address": "新北市新店區新店路",
            "description": "碧潭湖畔環境清幽，步道平坦，適合悠閒地帶狗散步。",
            "rating": 4.4,
            "tags": ["湖畔", "步道", "寵物友善"],
            "image_url": "https://picsum.photos/seed/newtp2/400/250",
        },
        {
            "id": 6,
            "name": "八里左岸公園",
            "address": "新北市八里區渡船頭路",
            "description": "河濱公園廣闊，視野開闊，設有狗狗活動區域。",
            "rating": 4.5,
            "tags": ["河濱", "公園", "寵物友善"],
            "image_url": "https://picsum.photos/seed/newtp3/400/250",
        },
    ],
    "台中市": [
        {
            "id": 7,
            "name": "台中都會公園",
            "address": "台中市西屯區環中路二段",
            "description": "廣大的都市公園，設有完善的步道系統，是台中市民帶狗散步的好去處。",
            "rating": 4.6,
            "tags": ["公園", "步道", "寵物友善"],
            "image_url": "https://picsum.photos/seed/taichung1/400/250",
        },
        {
            "id": 8,
            "name": "高美濕地",
            "address": "台中市清水區高美濕地",
            "description": "夕陽時分美不勝收，木棧道沿伸入濕地，是獨特的散步體驗。",
            "rating": 4.8,
            "tags": ["濕地", "步道", "景觀"],
            "image_url": "https://picsum.photos/seed/taichung2/400/250",
        },
        {
            "id": 9,
            "name": "柳川水岸步道",
            "address": "台中市西區柳川西路",
            "description": "整治後的柳川河岸，綠意盎然，是台中市區內的優質散步路線。",
            "rating": 4.3,
            "tags": ["河濱", "步道", "市區"],
            "image_url": "https://picsum.photos/seed/taichung3/400/250",
        },
    ],
    "台南市": [
        {
            "id": 10,
            "name": "台南都會公園",
            "address": "台南市北區環河北路",
            "description": "廣大的公園綠地，有多種運動設施，寵物友善環境佳。",
            "rating": 4.4,
            "tags": ["公園", "草地", "寵物友善"],
            "image_url": "https://picsum.photos/seed/tainan1/400/250",
        },
        {
            "id": 11,
            "name": "四草野生動物保護區步道",
            "address": "台南市安南區台江國家公園",
            "description": "被譽為台版亞馬遜，紅樹林步道生態豐富，帶狗來探索自然。",
            "rating": 4.7,
            "tags": ["生態", "步道", "紅樹林"],
            "image_url": "https://picsum.photos/seed/tainan2/400/250",
        },
        {
            "id": 12,
            "name": "奇美博物館周邊公園",
            "address": "台南市仁德區文華路二段66號",
            "description": "博物館外圍的廣大公園，歐式風情，是拍照散步的絕佳場所。",
            "rating": 4.6,
            "tags": ["公園", "景觀", "寵物友善"],
            "image_url": "https://picsum.photos/seed/tainan3/400/250",
        },
    ],
    "高雄市": [
        {
            "id": 13,
            "name": "駁二藝術特區周邊",
            "address": "高雄市鹽埕區大勇路1號",
            "description": "文創藝術園區旁的港邊步道，適合帶狗一起欣賞港灣風光。",
            "rating": 4.5,
            "tags": ["港灣", "步道", "文創"],
            "image_url": "https://picsum.photos/seed/kaohsiung1/400/250",
        },
        {
            "id": 14,
            "name": "蓮池潭風景區",
            "address": "高雄市左營區蓮池潭路",
            "description": "著名的龍虎塔旁，湖畔步道寬敞，環境清幽適合散步。",
            "rating": 4.4,
            "tags": ["湖畔", "步道", "景觀"],
            "image_url": "https://picsum.photos/seed/kaohsiung2/400/250",
        },
        {
            "id": 15,
            "name": "柴山自然公園",
            "address": "高雄市鼓山區龍子路",
            "description": "有台灣彌猴出沒的山林步道，挑戰性十足，帶狗一起登山探險。",
            "rating": 4.6,
            "tags": ["山林", "步道", "生態"],
            "image_url": "https://picsum.photos/seed/kaohsiung3/400/250",
        },
    ],
    "桃園市": [
        {
            "id": 16,
            "name": "虎頭山環保公園",
            "address": "桃園市桃園區成功路三段",
            "description": "桃園市區內的山林公園，步道完善，是帶狗爬山的好選擇。",
            "rating": 4.3,
            "tags": ["山林", "步道", "公園"],
            "image_url": "https://picsum.photos/seed/taoyuan1/400/250",
        },
        {
            "id": 17,
            "name": "石門水庫環湖步道",
            "address": "桃園市大溪區復興路",
            "description": "水庫湖畔的步道景色壯觀，空氣清新，適合長距離散步。",
            "rating": 4.7,
            "tags": ["湖畔", "步道", "景觀"],
            "image_url": "https://picsum.photos/seed/taoyuan2/400/250",
        },
        {
            "id": 18,
            "name": "大溪老街河濱公園",
            "address": "桃園市大溪區河濱路",
            "description": "大漢溪旁的廣闊河濱公園，視野遼闊，是假日帶狗散步的好去處。",
            "rating": 4.4,
            "tags": ["河濱", "公園", "寵物友善"],
            "image_url": "https://picsum.photos/seed/taoyuan3/400/250",
        },
    ],
    "新竹市": [
        {
            "id": 19,
            "name": "新竹都城隍廟周邊公園",
            "address": "新竹市北區中山路75號",
            "description": "廟宇周邊的市區公園，熱鬧又舒適，適合短距離散步。",
            "rating": 4.1,
            "tags": ["市區", "公園", "短程"],
            "image_url": "https://picsum.photos/seed/hsinchu1/400/250",
        },
        {
            "id": 20,
            "name": "青草湖風景區",
            "address": "新竹市東區青草湖路",
            "description": "湖光山色，環湖步道平坦，適合帶狗悠閒漫步。",
            "rating": 4.5,
            "tags": ["湖畔", "步道", "景觀"],
            "image_url": "https://picsum.photos/seed/hsinchu2/400/250",
        },
    ],
    "宜蘭縣": [
        {
            "id": 21,
            "name": "冬山河親水公園",
            "address": "宜蘭縣冬山鄉冬山路",
            "description": "親水公園環境優美，河岸步道寬廣，是宜蘭帶狗散步的首選。",
            "rating": 4.7,
            "tags": ["河濱", "公園", "寵物友善"],
            "image_url": "https://picsum.photos/seed/yilan1/400/250",
        },
        {
            "id": 22,
            "name": "羅東運動公園",
            "address": "宜蘭縣羅東鎮公園路",
            "description": "完善的運動設施與大片草坪，是毛孩奔跑玩耍的天堂。",
            "rating": 4.6,
            "tags": ["公園", "草地", "寵物友善"],
            "image_url": "https://picsum.photos/seed/yilan2/400/250",
        },
    ],
}

CITIES = list(WALKING_SPOTS.keys())
